# Generated by Django 2.2.7 on 2019-11-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SP",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("base_url", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.CharField(max_length=100)),
                ("x509_certificate", models.TextField(blank=True)),
                ("private_key", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={"verbose_name": "service provider",},
        ),
        migrations.CreateModel(
            name="IdP",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=100)),
                ("metadata_url", models.CharField(blank=True, max_length=500, verbose_name="Metadata URL")),
                ("metadata_xml", models.TextField(blank=True, verbose_name="Metadata XML")),
                ("lowercase_encoding", models.BooleanField(default=False, help_text="Check this if using ADFS.")),
                (
                    "saml_settings",
                    models.TextField(blank=True, help_text="Settings imported and used by the python-saml library."),
                ),
                ("last_import", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, default=None, null=True)),
                ("sp", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="idps", to="sp.SP")),
            ],
            options={"verbose_name": "identity provider", "unique_together": {("sp", "slug")},},
        ),
        migrations.CreateModel(
            name="IdPAttribute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saml_attribute", models.CharField(max_length=200)),
                ("mapped_name", models.CharField(blank=True, max_length=200)),
                ("is_nameid", models.BooleanField(default=False, verbose_name="Is NameID")),
                (
                    "idp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="sp.IdP"
                    ),
                ),
            ],
            options={
                "verbose_name": "identity provider attribute",
                "verbose_name_plural": "identity provider attributes",
                "unique_together": {("idp", "saml_attribute")},
            },
        ),
    ]
