# Generated by Django 3.2.8 on 2021-11-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sp', '0001_initial'), ('sp', '0002_auto_20191205_1758'), ('sp', '0003_auto_20200331_1934'), ('sp', '0004_auto_20200401_1328'), ('sp', '0005_auto_20210323_1526')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('base_url', models.CharField(help_text='Root URL for the site, including http/https, no trailing slash.', max_length=200, verbose_name='Base URL')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('x509_certificate', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('certificate_expires', models.DateTimeField(blank=True, null=True)),
                ('metadata_url', models.URLField(blank=True, help_text='Leave this blank if entering metadata XML directly.', max_length=500, verbose_name='Metadata URL')),
                ('verify_metadata_cert', models.BooleanField(default=True, verbose_name='Verify metadata URL certificate')),
                ('metadata_xml', models.TextField(blank=True, help_text='Automatically loaded from the metadata URL, if specified. Otherwise input directly.', verbose_name='Metadata XML')),
                ('lowercase_encoding', models.BooleanField(default=False, help_text='Check this if the identity provider is ADFS.')),
                ('saml_settings', models.TextField(blank=True, editable=False, help_text='Settings imported and used by the python-saml library.')),
                ('last_import', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('respect_expiration', models.BooleanField(default=False, help_text='Expires the Django session based on the IdP session expiration. Only works when using SESSION_SERIALIZER=PickleSerializer.', verbose_name='Respect IdP session expiration')),
                ('login_redirect', models.CharField(blank=True, help_text='URL name or path to redirect after a successful login.', max_length=200)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authenticate_method', models.CharField(blank=True, max_length=200)),
                ('login_method', models.CharField(blank=True, max_length=200)),
                ('auth_case_sensitive', models.BooleanField(default=True, verbose_name='NameID is case sensitive')),
                ('create_users', models.BooleanField(default=True, verbose_name='Create users that do not already exist')),
                ('entity_id', models.CharField(blank=True, help_text='Leave blank to automatically use the metadata URL.', max_length=200, verbose_name='Entity ID')),
                ('url_params', models.JSONField(default=None, help_text='Application-specific URL path parameters.', null=True, unique=True, verbose_name='URL Parameters')),
            ],
            options={
                'verbose_name': 'identity provider',
            },
        ),
        migrations.CreateModel(
            name='IdPUserDefaultValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_defaults', to='sp.idp', verbose_name='identity provider')),
            ],
            options={
                'verbose_name': 'user default value',
                'verbose_name_plural': 'user default values',
                'unique_together': {('idp', 'field')},
            },
        ),
        migrations.CreateModel(
            name='IdPAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saml_attribute', models.CharField(max_length=200)),
                ('mapped_name', models.CharField(blank=True, max_length=200)),
                ('is_nameid', models.BooleanField(default=False, help_text='Check if this should be the unique identifier of the SSO identity.', verbose_name='Is NameID')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sp.idp', verbose_name='identity provider')),
                ('always_update', models.BooleanField(default=False, help_text='Update this mapped user field on every successful authentication. By default, mapped fields are only set on user creation.', verbose_name='Always Update')),
            ],
            options={
                'verbose_name': 'attribute mapping',
                'verbose_name_plural': 'attribute mappings',
                'unique_together': {('idp', 'saml_attribute')},
            },
        ),
    ]
