# Generated by Django 2.2.7 on 2019-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idpattribute',
            name='always_update',
            field=models.BooleanField(default=False, help_text='If checked, the mapped_name for this attribute will always be updated upon successful authentication.', verbose_name='Always Update'),
        ),
    ]
