# Generated by Django 3.0.4 on 2020-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0002_auto_20191205_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="base_url",
            field=models.CharField(
                help_text=(
                    "Root URL for the site, including http/https, no trailing slash."
                ),
                max_length=200,
                verbose_name="Base URL",
            ),
        ),
        migrations.AlterField(
            model_name="idpattribute",
            name="is_nameid",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Check if this should be the unique identifier of the SSO "
                    "identity."
                ),
                verbose_name="Is NameID",
            ),
        ),
    ]
