# Generated by Django 3.0.4 on 2020-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0003_auto_20200331_1934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="authenticate_method",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="idp",
            name="base_url",
            field=models.CharField(
                help_text=(
                    "Root URL for the site, including http/https, no trailing slash."
                ),
                max_length=200,
                verbose_name="Base URL",
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="login_method",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
