# Generated by Django 3.1.7 on 2021-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0004_auto_20200401_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="url_params",
            field=models.JSONField(
                verbose_name="URL Parameters",
                default=None,
                null=True,
                help_text="Application-specific URL path parameters.",
            ),
        ),
    ]
