# Generated by Django 3.1.7 on 2021-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0006_remove_idp_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="url_params",
            field=models.JSONField(
                verbose_name="URL Parameters",
                default=dict,
                blank=True,
                help_text="Application-specific URL path parameters.",
            ),
        ),
    ]
