# Generated by Django 3.1.7 on 2021-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0007_auto_20210323_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="logout_method",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="idp",
            name="logout_redirect",
            field=models.CharField(
                blank=True,
                help_text="URL name or path to redirect after logout.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="idp",
            name="logout_triggers_slo",
            field=models.BooleanField(
                verbose_name="Logout triggers SLO",
                default=False,
                help_text=(
                    "Whether logging out should trigger a SLO request to the IdP."
                ),
            ),
        ),
        migrations.AddField(
            model_name="idp",
            name="state_timeout",
            field=models.IntegerField(
                default=60,
                help_text=(
                    "Time (in seconds) the SAML login request state is valid for."
                ),
            ),
        ),
    ]
