# Generated by Django 3.1.7 on 2021-03-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sp", "0008_auto_20210323_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdPUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameid", models.CharField(db_index=True, max_length=200)),
                ("user_id", models.CharField(max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idp_users",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "idp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="sp.idp",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("idp", "content_type", "user_id"),
                    ("idp", "nameid"),
                },
            },
        ),
    ]
