# Generated by Django 3.1.7 on 2021-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0009_idpuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="associate_users",
            field=models.BooleanField(
                default=True,
                verbose_name="Associate existing users with this IdP by username",
            ),
        ),
        migrations.AddField(
            model_name="idp",
            name="username_prefix",
            field=models.CharField(
                blank=True,
                max_length=20,
                help_text="Prefix for usernames generated by this IdP",
            ),
        ),
        migrations.AddField(
            model_name="idp",
            name="username_suffix",
            field=models.CharField(
                blank=True,
                max_length=20,
                help_text="Suffix for usernames generated by this IdP",
            ),
        ),
    ]
