# Generated by Django 3.2.8 on 2021-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0010_auto_20210326_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='url_params',
            field=models.JSONField(blank=True, default=dict, help_text='Application-specific URL path parameters.', verbose_name='URL Parameters'),
        ),
    ]
