# Generated by Django 4.0.5 on 2022-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sp", "0012_idp_authn_comparison_idp_authn_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="prepare_request_method",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="idp",
            name="update_user_method",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
