# Generated by Django 4.2.7 on 2023-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sp", "0013_idp_prepare_request_method_idp_update_user_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idp",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "identity provider",
            },
        ),
        migrations.AddField(
            model_name="idp",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
