# Generated by Django 5.0 on 2023-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sp", "0014_alter_idp_options_idp_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="logout_request_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="idp",
            name="logout_response_signed",
            field=models.BooleanField(default=False),
        ),
    ]
